 <?php
use BlushMe\Checkout\Block\ExtraSell as B; /* @var B $block */ $b = $block; /** @var B $b */
use Magento\Framework\View\TemplateEngine\Php as T; /** @var T $this */
$label_helper = $this->helper("Codazon\ProductLabel\Helper\Data");  // CUSTOM CODE
/** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
$extra_sell_products = $b->getExtraSellProducts();
$exist = count($extra_sell_products) > 0 ? true : false;
if ($exist) {
	$type = 'related';
	$class = $type;
	$image = 'related_products_list';
	$image_hover = 'related_products_list_hover';
	$description = $b->getExtraSellDescription();
	$items = $extra_sell_products;
}
if ($exist): ?>
<div class="cross-sell-products-container klarna-extra-sell-products">
	<div class="block <?= $class; ?>">
    	<div class="block-title title">
        	<strong id="block-<?= $class ?>-heading" role="heading" aria-level="2"><?= df_cfg("klarna/settings/extra_sell_title") ?></strong>
    	</div> 
    	<div class="block-description"><?php echo $description; ?></div> 

	    <div class="related-crossell block-content content bottom-products" aria-labelledby="block-<?= $class?>-heading">
	        <div class="products wrapper grid products-grid products-<?= $type; ?>">
	            <ol class="products list items product-items" id="slider-extra-sell-products">
	                <?php $iterator = 1; ?>
	                <?php foreach ($items as $_item): ?>
	                <?=($iterator++ == 1) ? '<li class="item product product-item" value="'.$_item->getId().'">' : '</li><li class="item product product-item" value="'.$_item->getId().'">' ?>
	               <input type="hidden" class="product_id" value="<?php echo $_item->getId()?>"/>
	                <div class="product-item-info">
	                	<div class="cdz-hover-section">                          
							<div class="cdz-product-top">
								<?= '<!-- ' . $image . '-->' ?>
								<a href="<?= $_item->getProductUrl(); ?>" class="product photo product-item-photo">						
									<span class="hover-image">
										<?php echo $b->getImage($_item, $image_hover)->toHtml(); ?>
									</span>
								</a>
								<?php $label_helper->showLabel($_item); ?> 
							</div>                           
	                    </div>
	                    
	               
							<div class="product details product-item-details">
								<div class="name-brand-content">
									<strong class="product name product-item-name"><a class="product-item-link link-<?php echo $_item->getId()?>" title="<?php echo $b->escapeHtml($_item->getName()) ?>" href="<?= $b->getProductUrl($_item) ?>">
										<?php echo $b->escapeHtml($_item->getName()) ?></a>
									</strong>
									<?php echo $this->getLayout()->createBlock("Seavus\Products\Block\Product\View")->setTemplate("Seavus_Products::product/view/brand.phtml")->setProduct($_item)->setExcludeBrandUrl(true)->toHtml(); ?>                 
								    <div class="raiting-content-grid product-explanation-attribute">
								  <?php echo $this->getLayout()->createBlock("Seavus\Products\Block\Product\View")->setTemplate("Seavus_Products::product/view/product_explanation.phtml")->setProduct($_item)->toHtml(); ?>              								
								</div>
								</div>
	                             <div class="raiting-content-grid">
	                                <?php echo $b->getReviewsSummaryHtml($_item, null) ?>
	                            </div>	 						
																				                 						
								<?= $b->getProductPrice($_item); ?>						
													
								<?php echo $this->getLayout()->createBlock("Seavus\Products\Block\Product\View")->setTemplate("Seavus_Products::product/view/recommended_price.phtml")->setProduct($_item)->toHtml(); ?>
								
								<div class="add-tocart-button">									
									<?php if ($_item->isSaleable()){ ?>
										<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
											<button class="action tocart primary show-tooltip" data-mage-init='{"redirectUrl": {"url": "<?= $b->getAddToCartUrl($_item) ?>"}}' type="button" title="<?= __('Add to Cart') ?>">
												<span><?= __('Add to Cart') ?></span>
											</button>
										<?php else: ?>
											<?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
											$postData = $postDataHelper->getPostData($b->getAddToCartUrl($_item), ['product' => $_item->getEntityId()]);
											$postParams = json_decode($postData,true);
											?>
											<form data-role="tocart-form" action="<?= $postParams['action']; ?>" method="post">
											   	<input type="hidden" name="product" value="<?= $postParams['data']['product']; ?>">												
									           	<input type="hidden" value="<?php echo __('Adding...')?>" name="BtnWhileAdding"/>
									            <input type="hidden" value="<?php echo __('Added')?>" name="BtnTextAdded"/>
									            <input type="hidden"  value="<?php echo __('Add to Cart')?>" name="BtnTextDefault"/>
												<?php echo $b->getBlockHtml('formkey'); ?>
												<button type="submit"
														title="<?php echo $b->escapeHtml(__('Buy')); ?>"
														class="action tocart primary" />
														<!-- id="product-addtocart-button" -->
													<span><?= __('Buy') ?></span>
												</button>
											</form>														
										<?php endif; ?>
									<?php } ?>
								</div>		
	                        </div>
	                    </div>
	                    <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
	                <?php endforeach ?>
	            </ol>
	        </div>
	    </div>
	</div>
 <?php if (false/*!$b->isRedirectToCartEnabled()*/) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
<?php endif; ?>

<script type="text/javascript">
require([
    'jquery',
    'slick'
], function ($) { 
        $(".related-crossell.bottom-products .products-related .product-items").not('.slick-initialized').slick({
            dots: false,
            infinite: false,         
            arrows:true,
            speed: 300,
            slidesToShow: 4,
            slidesToScroll: 4,
            adaptiveHeight:true,
            lazyLoad: 'ondemand',
            responsive: [
                {
                    breakpoint: 1280,
                    settings: {
                        slidesToShow: 4,
                        slidesToScroll: 4
                    }
                },
                {
                    breakpoint: 960,
                    settings: {
                        slidesToShow: 3,
                        slidesToScroll: 3
                    }
                },
                {
                    breakpoint: 768,
                    settings: {
                        slidesToShow: 3,
                        slidesToScroll: 3
                    }
                },
                {
                    breakpoint: 600,
                    settings: {
                        slidesToShow: 3,
                        slidesToScroll: 3,
                        dots: false,
                        arrows:true,
                        autoplay: false,
                        autoplaySpeed: 5000
                        
                    }
                }
            ]
        });
        $(".block-title").show();
        function getRows(selector) {
		    var height = $(selector).height();
		    var line_height = $(selector).css('line-height');
		    line_height = parseFloat(line_height);
		    var rows = height / line_height;
		    return Math.round(rows);
		}
        $(".klarna-extra-sell-products li.item.product.product-item").each(function() {
        	var id= $(this).attr('value');
        	var product_link= $('.link-'+id);

        	if(getRows(product_link)>=2){
				$('.klarna-extra-sell-products .products.list.items').addClass('multiline');
			}
        });
      
});
</script>

</div>
<?php endif;?>