<?php
use BlushMe\Checkout\Block\Extra as ParentB; /* @var ParentB $parent */
use BlushMe\Checkout\Block\Extra\Item as B; /* @var B $block */ $b = $block; /** @var B $b */
use Codazon\ProductLabel\Helper\Data as CodazonH;
use Magento\Catalog\Block\Product\AbstractProduct as PB;
use Magento\Catalog\Model\Product as P; /** @var P $p */
use Magento\Framework\View\TemplateEngine\Php as T; /** @var T $this */
$codazonH = $this->helper(CodazonH::class); /** @var CodazonH $codazonH */
$pb = df_product_b(); /** @var PB $pb */
?>
<li class='item product product-item' value='<?= $p->getId() ?>'>
	<input class='product_id' type='hidden' value='<?= $p->getId()?>' />
	<div class='product-item-info'>
		<div class='cdz-hover-section'>
			<div class='cdz-product-top'>
				<a class='product photo product-item-photo' href='<?= $p->getProductUrl(); ?>'>
					<span class='hover-image'>
						<?= $pb->getImage($p, 'related_products_list_hover')->toHtml(); ?>
					</span>
				</a>
				<?php $codazonH->showLabel($p); ?>
			</div>
		</div>
		<div class='product details product-item-details'>
			<div class='name-brand-content'>
				<strong class='product name product-item-name'>
					<a
						class='product-item-link link-<?= $p->getId()?>'
						href='<?= $pb->getProductUrl($p) ?>'
						title='<?= $b->escapeHtml($p->getName()) ?>'
					><?= $b->escapeHtml($p->getName()) ?></a>
				</strong>
				<?= $b->part('brand', ['exclude_brand_url' => true]) ?>
				<div class="raiting-content-grid product-explanation-attribute">
					<?= $b->part('product_explanation') ?>
				</div>
			</div>
			<div class="raiting-content-grid"><?= $pb->getReviewsSummaryHtml($p, null) ?></div>
			<?= $pb->getProductPrice($p); ?>
			<?= $b->part('recommended_price') ?>
			<div class="add-tocart-button">
				<?php if ($p->isSaleable()) {
					if ($p->getTypeInstance()->hasRequiredOptions($p)) {
						echo df_tag('button', [
							'class' => 'action tocart primary show-tooltip'
							,'data-mage-init' => df_json_encode(['redirectUrl' => ['url' => $pb->getAddToCartUrl($p)]])
							,'title' => __('Add to Cart')
						], df_tag('span', [], __('Add to Cart')));
					}
					else {
						$postParams = json_decode(df_post_h()->getPostData(
							$pb->getAddToCartUrl($p), ['product' => $p->getEntityId()]
						), true);
						?>
						<form action="<?= $postParams['action']; ?>" data-role="tocart-form" method="post">
							<?= df_cc_n(
								$b->hidden('product', $postParams['data']['product'])
								,$b->hidden('BtnWhileAdding', __('Adding...'))
								,$b->hidden('BtnTextAdded', __('Added'))
								,$b->hidden('BtnTextDefault', __('Add to Cart'))
								,$b->getBlockHtml('formkey')
							)?>
							<button
								class="action tocart primary"
								title="<?= $b->escapeHtml(__('Buy')); ?>"
								type="submit"
							><span><?= __('Buy') ?></span></button>
						</form>
					<?php } ?>
				<?php } ?>
			</div>
		</div>
	</div>
</li>